version: '3'
services:
  mssql-turbin-sikker:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Turbinsikker101
    volumes:
      - './drive:/var/opt/mssql'
    command: /opt/mssql/bin/sqlservr
